server:
  port: 7130

spring:
  application:
    name: springcloud-eureka-client-customer

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7100/eureka/ #Eureka地址



