server:
  port: 7160

spring:
  application:
    name: springcloud-nacos-client-customer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoint:
    web:
      exposure:
        include: "*"


